app = "previdencia-2025-plw27a"
primary_region = "gig"

[build]
  builder = "heroku/builder:22"

[env]
  PORT = "3000"
  NODE_ENV = "production"

[http_service]
  auto_start_machines = true
  auto_stop_machines = false
  force_https = true
  internal_port = 3000
  min_machines_running = 1
  processes = ["app"]

[[mounts]]
  source = "data"
  destination = "/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
  memory_mb = 1024

[deploy]
  release_command = "npm run migrate:prod && npm run seed"