app = "previdencia-2025-plw27a"
primary_region = "gig"

[build]
  builder = "heroku/builder:22"

[env]
  PORT = "3000"

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 3000
  min_machines_running = 0
  processes = ["app"]

[[mounts]]
  destination = "/data"
  source = "data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
  memory_mb = 1024
